# Generated by Django 6.0 on 2026-03-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_message_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='age_group',
            field=models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-50', '36-50'), ('50+', '50+')], max_length=50),
        ),
    ]
