# Generated by Django 6.0 on 2026-03-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_voter_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='age_group',
        ),
    ]
