# Generated by Django 6.0 on 2026-03-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_voter_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='clan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
